name: Regenerate Protobuf Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  regenerate-protobuf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Include the pull request ref in the checkout action to prevent merge commit
        # https://github.com/actions/checkout?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"

      - name: Install task CLI
        run: |
          TASK_VERSION=3.39.0
          curl -sL https://github.com/go-task/task/releases/download/v${TASK_VERSION}/task_linux_amd64.tar.gz | tar -xz -C /usr/local/bin task

      - name: Install protoc
        run: |
          PROTOC_VERSION=28.1
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d protoc3
          sudo mv protoc3/bin/* /usr/local/bin/
          sudo mv protoc3/include/* /usr/local/include/
          rm -rf protoc3 protoc-${PROTOC_VERSION}-linux-x86_64.zip
    
      - name: Install dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

      - name: Regenerate protobuf files
        run: |
          task proto:all

      - uses: planetscale/ghcommit-action@v0.1.45
        with:
          commit_message: "🤖 regenerate protobuf files"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: '*.pb.go'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
