name: Regenerate Protobuf Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  regenerate-protobuf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.0"

      - name: Install task CLI
        run: |
          TASK_VERSION=3.39.0
          curl -sL https://github.com/go-task/task/releases/download/v${TASK_VERSION}/task_linux_amd64.tar.gz | tar -xz -C /usr/local/bin task

      - name: Install protoc
        run: |
          PROTOC_VERSION=28.1
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d protoc3
          sudo mv protoc3/bin/* /usr/local/bin/
          sudo mv protoc3/include/* /usr/local/include/
          rm -rf protoc3 protoc-${PROTOC_VERSION}-linux-x86_64.zip
    
      - name: Install dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

      - name: Regenerate protobuf files
        run: |
          task proto:all

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Regenerate protobuf files"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
